config/routes.rb
JacobBlog::Application.routes.draw do
	get 'tags/:tag', to: 'posts#index', as: :tag
	get 'type/:type', to: 'posts#index', as: :type
	get 'archive', to: 'posts#index', :archive => true, as: "archive"
	get 'admin', to: 'posts#admin', as: "admin"
	get 'login', to: 'sessions#new', as: "login"
	get 'logout', to: 'sessions#destroy', as: "logout"
	root :to => 'posts#index'
	resources :posts, :resources, :sessions, :users
end

app/models/post.rb
class Post < ActiveRecord::Base
	is_impressionable 
	
	attr_accessible :title, :content, :post_type, :user_id, :tag_list, :html, :url 
	acts_as_taggable
	belongs_to :user
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	attr_accessible :url
end

app/models/user.rb
class User < ActiveRecord::Base
	include Gravtastic
	gravtastic :size => 200
	attr_accessible :email, :name, :password, :password_confirmation, :about
	has_many :posts
	has_secure_password
	validates_presence_of :password, :on => :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery

	private

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	
	def check_admin
		if !current_user
			redirect_to login_url
		end
	end

	helper_method :check_admin
	helper_method :current_user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :check_admin, :only => [:new, :create, :edit, :update, :admin, :destroy]
	impressionist :actions=>[:show]

	def index
		if params[:tag]
			@posts = Post.tagged_with(params[:tag]).reverse
		elsif params[:type]
			@posts = Post.all.select{|p| p.post_type == params[:type]}.reverse
		elsif params[:archive]
			@posts = Post.all.reverse
			@archive = params[:archive]
		else
			@posts = Post.all.reverse[0..15]
		end
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(params[:post])
		@post.save
		redirect_to root_url
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		@post.update_attributes(params[:post])
		@post.save
		redirect_to root_url
	end

	def show
		@post = Post.find(params[:id])
		respond_to do |f|
			f.html
			f.js
		end
	end

	def admin
		@posts = Post.all.reverse
		@resources = Resource.all
		@user = User.find(1)
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to root_url
	end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
	before_filter :check_admin, :only => [:new, :create, :edit, :update, :destroy]

	def index
		@resources = Resource.all
	end

	def new
		@resource = Resource.new
	end

	def create
		@resource = Resource.new(params[:resource])
		@resource.save
		redirect_to resources_url
	end

	def edit
		@resource = Resource.find(params[:id])
	end

	def update
		@resource = Resource.find(params[:id])
		@resource.update_attributes(params[:resource])
		redirect_to resources_url
	end

	def destroy
		@resource = Resource.find(params[:id])
		@resource.destroy
		redirect_to admin_url
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_url
		else
			render "new"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :check_admin, :only => [:edit, :update]

	# def new
	# 	@user = User.new
	# end

	# def create
	# 	@user = User.new(params[:user])
	# 	@user.save
	# 	redirect_to root_url
	# end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update_attributes(params[:user])
		redirect_to admin_url
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= @title + " | " if @title %>Jacob's Blog</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<link rel="shortcut icon" href="/favicon.png" type="image/png">
		<link rel="shortcut icon" type="image/png" href="/favicon.png" />
		<%= favicon_link_tag "favicon.png" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<header>
			<div class="container">
				<nav class="sixteen columns">
					<div class="five columns">
						<%= link_to root_url do %>
							<h1 class="left">
								Jacob's Blog
							</h1>
						<% end %>
					</div>
					<div class="ten columns">
						<ul class="right">
							<li>
								<%= link_to "Home", root_url%>
							</li>
							<li>
								<%= link_to "Resources", resources_url %>
							</li>
							<li>
								<%= link_to "Archive", archive_url %>
							</li>
							<% if current_user %>
								<li>
									<%= link_to "Admin", admin_url %>
								</li>
								<li>
									<%= link_to "Logout", logout_url %>
								</li>
							<% end %>
						</ul>
				</nav>
			</div>
		</header>


		<hr>

		<div class="container body">
			<div class="sixteen columns">
				<div class="half centered">
					<%= yield %>
				</div>
			</div>
		</div>

		<div class="modal bg"></div>
		<div class="modal body"></div>
	</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<%= f.label :post_type %>
	<%= f.select :post_type, options_for_select([
		['Article', 'article'],
		['Video', 'video'],
		['Link', 'link']],
		(if @post.post_type
			@post.post_type
		else
			'article'
		end)
	) %> <br>

	<%= f.label :title %>
	<%= f.text_field :title %> <br>

	<%= f.label :tag_list, "Tags (separate by commas)" %>
	<%= f.text_field :tag_list %> <br>

	<%= f.label :content, "Content (Intro/Main Text)" %>
	<%= f.text_area :content %> <br>

	<%= f.label :html, "Paste YouTube HTML", :data => {"show-on" => "video"}, :class => 'hidden' %>
	<%= f.text_area :html, :data => {"show-on" => "video"}, :class => 'hidden' %>

	<%= f.label :url, :data => {"show-on" => "link"}, :class => 'hidden' %>
	<%= f.text_field :url, :data => {"show-on" => "link"}, :class => 'hidden' %> <br data-show-on="link" class="hidden">

	<%= f.hidden_field :user_id, :value => 1 %>

	<%= f.submit %>
<% end %>

app/views/posts/_modal.html.erb
<% if modal %>
	<%= link_to "permalink", @post, :class => "posts show permalink" %>
<% end %>
<h2 class="posts show title"><%= @post.title %></h2>
<section class="posts show meta">
	<span class="posts show author">by <%= @post.user.name %></span>
	<span class="posts show date">on <%= @post.created_at.strftime("%m/%d/%Y") %></span><br>
	<%= render 'tags', :post => @post %>
</section>

<hr>


<div class="posts show body <%= @post.post_type %>">
	<p class="content">
		<%= @post.content %>
	</p>
	<% if @post.post_type == "video" %>
		<%= raw @post.html %>
		<script>
			$(".posts.show.video iframe").height(($(".posts.show.video iframe").width / $(".posts.show.video iframe").height) * 634)
			$(".posts.show.video iframe").width(634)
		</script>
	<% elsif @post.post_type == "link" %>
		<%= link_to @post.url, :class => "posts show link" do %>
			<h2><%= @post.url %></h2>
		<% end %>
	<% end %>
</div>

app/views/posts/_tags.html.erb
<%= link_to type_path(post.post_type), :class => "tag" do %>
	<%= post.post_type.split.map(&:capitalize).join(' ') %>
<% end %>
<% post.tag_list.each do |tag| %>
	<%= link_to tag_path(tag), :class => "tag" do %>
		<%= tag.split.map(&:capitalize).join(' ') %>
	<% end %>
<% end %>

app/views/posts/admin.html.erb
<% @title = "Admin" %>

<h1 class="form"> Admin </h1>

<hr>

<%= link_to "Edit About Me Text", edit_user_path(@user) %>

<hr>

<h3>Posts:</h3>
<ul>
	<li>
		<strong><%= link_to "New Post", new_post_path %></strong>
	</li>
	<% @posts.each do |post| %>
		<li><%= link_to post.title, post %> (<%= pluralize(post.impressionist_count(:filter=>:ip_address), "[unique] view") %>) - <%= link_to "Edit", edit_post_path(post) %> | <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></li>
	<% end %>
</ul>

<hr>

<h3>Resources:</h3>
<ul>
	<li>
		<strong><%= link_to "New Resource", new_resource_path %></strong>
	</li>
	<% @resources.each do |r| %>
		<li><%= link_to r.url, r.url %> - <%= link_to "Edit", edit_resource_path(r) %> | <%= link_to 'Delete', r, method: :delete, data: { confirm: 'Are you sure?' } %></li>
	<% end %>
</ul>

app/views/posts/edit.html.erb
<h1 class="form"> Edit Post </h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>
	<% if params[:type] %>
		Listing all <%= params[:type] + "s" %>
	<% elsif params[:tag] %>
		Posts tagged with "<%= params[:tag] %>"
	<% elsif @archive %>
		Archive
		<% @title = "Archive" %>
	<% else %>
		Welcome
		<% @title = "Welcome" %>
	<% end %>
</h1>
<div class="posts index">
	<ul class="posts list">
		<% @posts.each do |post| %>
			<hr>
			<li class="posts list-item">
				<%= link_to post.title, post, :class => "show-link", :remote => (not @archive ? true : false) %>
				<span class="posts author">by <%= post.user.name %></span>
				<span class="posts date">on <%= post.created_at.strftime("%m/%d/%Y") %></span><br>
				<section class="tags">
					<%= render 'tags', :post => post %>
				</section>
			</li>
		<% end %>
		<hr>
		<% if !params[:tag] and !params[:type] and !@archive %>
			<li class="posts list-item">
				<%= link_to archive_url, :class => "show-link" do %>
					 Archive &raquo;
				<% end %>
			</li>
			<hr>
		<% end %>
	</ul>
</div>

app/views/posts/new.html.erb
<h1 class="form"> New Post </h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<%= render 'modal', :locals => {:post => @post, :modal => false} %>

app/views/posts/show.js.erb
$(".modal.body").html("<%= escape_javascript render 'modal', :locals => {:post => @post}, :modal => true %>")
$(".modal").fadeIn()

app/views/resources/_form.html.erb
<%= form_for @resource do |f| %>
	<%= f.label :url %>
	<%= f.text_field :url %> <br>

	<%= f.submit %>
<% end %>

app/views/resources/edit.html.erb
<h1 class="form"> Edit Resource </h1>
<%= render 'form' %>

app/views/resources/index.html.erb
<% @title = "Resources" %>
<h1> Resources </h1>
<ul class="lst">
	<% @resources.each do |r| %>
		<li> <%= link_to r.url, r.url %> </li>
	<% end %>
</ul>

app/views/resources/new.html.erb
<h1 class="form"> New Resource </h1>
<%= render 'form' %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %><br>

	<%= f.label :email %>
	<%= f.email_field :email %><br>

	<%= f.label :about %>
	<%= f.text_area :about %><br>

	<%= f.label :password %>
	<%= f.password_field :password %><br>

	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %><br>

	<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1 class="form"> Edit Me </h1>
<%= render 'form' %>